[package]
name = "linphon"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Florian Breit <florian@florian.me.uk>"]
description = "Set phonological feature matrices, linear rewrite rules, and more."
repository = "https://github.com/thatfloflo/typst-linphon"
keywords = ["linguistics", "phonology", "rewrite rules"]
categories = ["components", "text", "paper"]
disciplines = ["linguistics"]
exclude = ["reference/", "README.md"]
compiler = "0.13.0"
